### ISSUE TITLE
Avoid fixed date in template

### ISSUE THREAD

**Issue by hturner** [rjournal/rjtools#101]
Comment from @ajrgodfrey

> The template article includes a fixed date in the YAML `date: "2022-11-09"`. It would be better to set the date programmatically, i.e. `date: "`r Sys.Date()`"`

I guess the fixed date is when the template was last updated, but this does not encourage good practice. Maybe the date of last update could be included in the main text instead.

**Comment by mitchelloharawild** [comment]
This should be added to the submission checks, but using a dynamic date will be problematic for our issue rendering process.
