### ISSUE TITLE
Prep submission functions

### ISSUE THREAD

**Issue by dicook** [rjournal/rjtools#106]
- [x] Argument should assume current directory because one would run the function from inside the folder for the article to be submitted (prep_submission, and zip_paper)
- [x] zip_paper() should ignore .aux, .log, .out files
- [x] More details on how to enter "others", or possibly more explicit, like data=NULL, figures=NULL, scripts=NULL. Generally more information on what files are automatically included and what files if present should be added.

**Comment by dicook** [comment]
- [ ] Prep_submission should return the values to be entered into the submission form as an object
- [ ] Keywords assistance is needed also

**Comment by huizezhang-sherry** [comment]
Now `check_folder_structure()` is run first inside `zip_paper()` and prompt users to fix if not SUCCESS, then it will zip everything under the main directory.
