### ISSUE TITLE
`web-only: true` still produce a pdf file

### ISSUE THREAD

**Issue by cderv** [rjournal/rjtools#110]
I found that `web_only: true` in YAML (which should be the default if I am right from [`rjournal_web_article`](https://rjournal.github.io/rjtools/reference/rjournal_article.html)) is still producing a PDF for me. 

I understand though it should be skipped in some cases
https://github.com/rjournal/rjtools/blob/0bbb1c7541fc18c193bc36244a48fcb039d9de7d/R/rj_web_article.R#L222-L223

but `render_pdf` does not seem to respect `web_only`
https://github.com/rjournal/rjtools/blob/0bbb1c7541fc18c193bc36244a48fcb039d9de7d/R/rj_web_article.R#L135C20-L135C45

Anyhow, you know better than me the code base, how to be sure to only produce HTML version which would be easier for me when I test stuff to compare with **distill* ? thanks

**Comment by Abhi-1U** [comment]
You can try out my forked copy of [rjtools](https://github.com/Abhi-1U/rjtools), The `web_only` param should work there as desired.

**Comment by mitchelloharawild** [comment]
Closing as the type of article (pdf stub or html conversion) will be based on the body contents after the migration is completed. Accordingly, `web_only` has been removed (still of course, available in the fork https://github.com/Abhi-1U/rjtools if needed..
