### ISSUE TITLE
paper-with-errors should probably have a different name on the paper

### ISSUE THREAD

**Issue by dicook** [rjournal/rjtools#14]
the paper-with-errors folder has a sample-article set of files, for providing examples for the check functions. to avoid confusion with the actual sample-article these should be renamed paper-with-errors, and the check functions need to have the name of file loaded changed to use this one

also make sure the package version is updated with the change. 

now that the package is publicly visibly, and people are testing it out, we need to do version updates with each code change

**Comment by huizezhang-sherry** [comment]
The article in the paper-with-errors fold is now labeled with "paper-with-errors".
