### ISSUE TITLE
Struggling with two types of plots in paper

### ISSUE THREAD

**Issue by dicook** [rjournal/rjtools#17]
I'm having trouble getting sizes right for both html and pdf outputs, and am thinking about how do we reference/link the figure in the text when there are two outputs?

**Comment by huizezhang-sherry** [comment]
Does the sizing to do with static graph or animation? With multiple outputs, does [tagging](https://patchwork.data-imaginist.com/articles/guides/annotation.html#tagging) in patchwork work?

**Comment by dicook** [comment]
Both seem to be problematic but can show you tomorrow.

Also, the issue of which chunk gets referenced in the text body - that’s a tough one.

**Comment by mitchelloharawild** [comment]
Closing as stale.
