### ISSUE TITLE
Clarify "Submission does not have consistently named tex, bib, and R files"?

### ISSUE THREAD

**Issue by maelle** [rjournal/rjtools#21]
I ran `rjtools::initial_check_article("paper")` and got the error copied in the issue title.

I had used `rjtools::create_article(filename = "response-commentary")` to create the article, and to render it

```r
rmarkdown::render("paper/response-commentary.Rmd", output_format = "rjtools::rjournal_web_article")
rmarkdown::render("paper/response-commentary.Rmd", output_format = "rjtools::rjournal_pdf_article")

```

**Comment by maelle** [comment]
I realized it means I had to rename the .bib but could it be renamed by `create_article()` directly?

**Comment by mitchelloharawild** [comment]
I've removed the check of .bib having the same file name.
Since we accept Rmd now we don't need to assume the file name of the appropriate bib and can look into the front matter to locate it.
