### ISSUE TITLE
Incorrect rendering of labels in equations (LaTeX)

### ISSUE THREAD

**Issue by pbiecek** [rjournal/rjtools#31]
I really like the look of the HTML papers. However, I have a problem with the equations and have not found a good solution.

I have following chunk of code:

```
\begin{equation} 
STP_{\textit{parity loss}} = \Big | \ln \Big( \frac{STP_b}{STP_a} \Big)\Big|. 
\end{equation} 

This notation is very helpful because it allows to accumulate $STP_{\textit{parity loss}}$ overall unprivileged subgroups, so not only in the binary case.

\begin{equation} 
STP_{\textit{parity loss}} = \sum_{i \in \{a, b, ...\}} \Big|\ln \Big(\frac{STP_i}{STP_a} \Big)\Big|.  
\label{eq:parityLoss}
  (\#eq:parityLoss)
\end{equation} 

Equation \@ref(eq:parityLoss)
```

I would like to refer to the second equation. In LaTeX I use `\label{eq:parityLoss}` and in markdown `(\#eq:parityLoss)`.

It renders like that in HTML:

<img width="743" alt="Screenshot 2022-03-07 at 9 55 22 PM" src="https://user-images.githubusercontent.com/4624318/157116436-f0a969e8-9dc9-4920-a8c7-0c11687d722f.png">

and like that in PDF:

<img width="866" alt="Screenshot 2022-03-07 at 9 55 59 PM" src="https://user-images.githubusercontent.com/4624318/157116500-7954f243-d4da-4aef-a0d6-cfee4c4adb54.png">

One problem is that in markdown some equations are not numbered, so the numbering of equations differs between HTML and PDF.

The second problem is that in PDF the label `(#eq : parityLoss)` does not disappear.

I have tried to deal with this by using conditional evaluation of R code chunks, but I have not been able to solve this problem.

Any suggestions are welcome!

**Comment by huizezhang-sherry** [comment]
The same issue was brought up in #26

**Comment by pbiecek** [comment]
Hi, the #26 is closed/solved, 
but the suggested solution is not working for equations

**Comment by mitchelloharawild** [comment]
The issue with `(#eq : parityLoss)` showing is due to specifying the label twice.

The correct code for this should be:

```latex

\begin{equation} 
STP_{\textit{parity loss}} = \Big | \ln \Big( \frac{STP_b}{STP_a} \Big)\Big|. 
\end{equation} 

This notation is very helpful because it allows to accumulate $STP_{\textit{parity loss}}$ overall unprivileged subgroups, so not only in the binary case.

\begin{equation} 
STP_{\textit{parity loss}} = \sum_{i \in \{a, b, ...\}} \Big|\ln \Big(\frac{STP_i}{STP_a} \Big)\Big|.  
  (\#eq:parityLoss)
\end{equation} 

Equation \@ref(eq:parityLoss)
```

As for the numbering issue, this is probably trickier to fix.

web:
![image](https://user-images.githubusercontent.com/16127127/165664824-667f0466-83ab-4639-8e42-f62f41aae20f.png)

pdf:
![image](https://user-images.githubusercontent.com/16127127/165664847-afd9a9c2-4312-4e2c-b47b-9e4809d92de2.png)

**Comment by mitchelloharawild** [comment]
The temporary quick fix for the inconsistent numbering is of course to always label equations, even if they aren't referred to.
I think the fix for numbering equations without labels will need to occur in the bookdown side of the html rendering.

**Comment by mitchelloharawild** [comment]
It seems that this is the documented behaviour of bookdown: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations

If you don't want to number equations, use an `equation*` environment.
If you want to number equations, use an `equation` environment **and** provide the label for it to be numbered. Bookdown does not automatically number `equation` environments.

**Comment by mitchelloharawild** [comment]
Closing as this is the documented behaviour of `bookdown::html_document2()`.
Labelling of equations, figures and tables should be done in accordance with the bookdown format.
