### ISSUE TITLE
How to use inline code in `rjtools`?

### ISSUE THREAD

**Issue by hope-data-science** [rjournal/rjtools#32]
What is the equivalent for `\code{}` in latex in `rjtools`? Thanks.

**Comment by dicook** [comment]
Backticks, just like you have used for rjtools in the title.

**Comment by hope-data-science** [comment]
Thank you for the feedback. I raise this question because when I copy some of my latex texts to rmd, it yields error. It seems that we could not use Chinese quotation mark in rmd, but this question is not caused by introducing the inline codes. Hopefully, there might be better way to detect why the problems comes out in the future. Thanks~
