### ISSUE TITLE
Markdown tables aren't correctly showing in PDF output

### ISSUE THREAD

**Issue by hope-data-science** [rjournal/rjtools#34]
In the template (<https://rjournal.github.io/rjtools/articles/article_template.html>), we can learn how to include data tables in `rjtools`. Is there a way to include tables as provided in <https://dereksonderegger.github.io/570L/15-rmarkdown-tricks.html>? Currently, I could not find a way to use other formats in the table (e.g. I might want to include a `\CRANpkg{}` or `[@]` for reference in the table).  How can I make a table like below (the references have links):
![image](https://user-images.githubusercontent.com/32947502/159407070-c4bc90f6-6487-4869-97d4-1f4f829eaf5f.png)

Thanks.

**Comment by mitchelloharawild** [comment]
This is possible with markdown tables, but it appears there is an issue with the PDF format. Something like this **should** (but doesn't completely) work:

```
@Book{plotly,
    author = {Carson Sievert},
    title = {{Interactive Web-Based Data Visualizatio}n with R, plotly, and shiny},
    publisher = {Chapman and Hall/CRC},
    year = {2020},
    isbn = {9781138331457},
    url = {https://plotly-r.com},
  }

@Manual{crosstalk,
  title = {{crosstalk}: Inter-Widget Interactivity for HTML Widgets},
  author = {Joe Cheng and Carson Sievert},
  year = {2021},
  note = {R package version 1.1.1},
  url = {https://CRAN.R-project.org/package=crosstalk},
}
```

````r
```{r}
tbl <- tibble::tribble(
  ~ package, ~ reference,
  "plotly", "[@plotly]",
  "crosstalk", "[@crosstalk]"
)
knitr::kable(tbl, escape = FALSE)
```
````

![image](https://user-images.githubusercontent.com/16127127/159583937-becdd27a-cdd0-4163-8528-2d10cb42be9f.png)
