### ISSUE TITLE
Duplicated pdf files exist in submission?

### ISSUE THREAD

**Issue by hope-data-science** [rjournal/rjtools#36]
In `check_wrappers` the package make sure that the two expected RJwrapper files (RJwrapper.tex and RJwrapper.pdf) exist. But when we knit the file, the RJwrapper.pdf would be removed and only filename.pdf exist at last. Is there a way to fix this? Or could we just submit the filename.pdf instead of RJwrapper.pdf?

Thanks.

**Comment by dicook** [comment]
Hi Hope,

knitting should create the RJwrapper.pdf. Do you want to share your github repo of your paper with me so that I can check the problem? ***@***.***)

> On 25 Mar 2022, at 12:40 am, Hope ***@***.***> wrote:
> 
> 
> In check_wrappers the package make sure that the two expected RJwrapper files (RJwrapper.tex and RJwrapper.pdf) exist. But when we knit the file, the RJwrapper.pdf would be removed and only filename.pdf exist at last. Is there a way to fix this? Or could we just submit the filename.pdf instead of RJwrapper.pdf?
> 
> Thanks.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by hope-data-science** [comment]
Hi Di,

Of course it would be OK to share the repo. Find the files in <https://github.com/hope-data-science/RJ_akc/article>. 

When I use "Knit" in Rstudio, the filename.pdf would come out, but no RJwrapper.pdf is left after knitting. If I want to get the RJwrapper.pdf, I can open the filename.pdf and knit again, or simply make a copy and rename the filename.pdf to RJwrapper.pdf.

I am not sure if the "Knit" is a correct way, because I also find `rjournal_pdf_article` function, I did not use it in my preparation. Hope this info would help. Thanks.

Cheers,
Hope

**Comment by mitchelloharawild** [comment]
Closing as `check_wrappers()` has been removed as wrappers are no longer required/expected as you describe.

**Comment by dicook** [comment]
I think it is a private repo - you’ll need to give my github name access to see it.

> On 25 Mar 2022, at 12:56 pm, Hope ***@***.***> wrote:
> 
> 
> Hi Di,
> 
> Of course it would be OK to share the repo. Find the files in https://github.com/hope-data-science/RJ_akc/article.
> 
> When I use "Knit" in Rstudio, the filename.pdf would come out, but no RJwrapper.pdf is left after knitting. If I want to get the RJwrapper.pdf, I can open the filename.pdf and knit again, or simply make a copy and rename the filename.pdf to RJwrapper.pdf.
> 
> I am not sure if the "Knit" is a correct way, because I also find rjournal_pdf_article function, I did not use it in my preparation. Hope this info would help. Thanks.
> 
> Cheers,
> Hope
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by dicook** [comment]
It compiles nicely for me. Only the file akc.pdf is created. 

All the initial_check_article() checks are successful, with the exception of some words to check spelling, and the title in title case. This latter one can be ignored because the package name is all lower case. We will be ignoring this in the next version of rjtools.

**Comment by hope-data-science** [comment]
Thank you for the feedback. I have no more questions on this issue.
