### ISSUE TITLE
The all lower case package name could not pass the title case check

### ISSUE THREAD

**Issue by hope-data-science** [rjournal/rjtools#37]
The package name is not always started by a capitial letter, when this happens, the submission check returns an error as below:

```
! ERROR: The title is not in title case! Suggest title to be changed to:
...
```
Is there a way to fix this?

Thanks.

**Comment by huizezhang-sherry** [comment]
Hi, the checks give *suggested* changes. 

If your title starts with a non-capitalised package name, I think it is fine to leave it as it is.

**Comment by dicook** [comment]
It could be nice to have an ignore parameter, with a list of words to ignore in the title, though. 

> On 25 Mar 2022, at 2:12 pm, Sherry Zhang ***@***.***> wrote:
> 
> 
> Hi, the checks give suggested changes.
> 
> If your title starts with a non-capitalised package name, I think it is fine to leave it as it is.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by dicook** [comment]
This check is primarily a warning. It is up to you to decide if it is correct, when this is flagged. 

If you have used a package name, then yes, it should be lower case. This is hard to automate, although, it is possible to add an “ignore” option to the function which would point to particular words that can be ignored for title case checking @huizezhange-sherry

> On 25 Mar 2022, at 2:02 pm, Hope ***@***.***> wrote:
> 
> 
> The package name is not always started by a capitial letter, when this happens, the submission check returns an error as below:
> 
> ! ERROR: The title is not in title case! Suggest title to be changed to:
> ...
> 
> Is there a way to fix this?
> 
> Thanks.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***
