### ISSUE TITLE
`\code{}` doesn't work for html output

### ISSUE THREAD

**Issue by willju-wangqian** [rjournal/rjtools#38]
`\code{}` works for pdf output, but not for HTML output.

I'm using `rjtools_1.0.0`

**Comment by dicook** [comment]
Hi Will,

Use backticks to delimit your code, please. This should work for both output formats.

eg `code`

> On 12 Apr 2022, at 12:31 pm, Wangqian (Will) Ju ***@***.***> wrote:
> 
> 
> \code{} works for pdf output, but not for HTML output.
> 
> I'm using rjtools_1.0.0
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by willju-wangqian** [comment]
Okay, thank you!
