### ISSUE TITLE
Add section numbering to the style

### ISSUE THREAD

**Issue by dicook** [rjournal/rjtools#39]

**Comment by casperhart** [comment]
This would be quite handy. I managed to get numbered sections in the HTML output by adding the `--number-sections` pandoc flag, but I haven't gotten this to work with PDF. I'd be happy to contribute but I'm a bit stuck, any advice would be appreciated. Cheers

**Comment by mitchelloharawild** [comment]
Some relevant discussion in `{distill}`: https://github.com/rstudio/distill/issues/56

I'm inclined to wait for numbering to be implemented in the distill package before adding the option for our PDF output.
The distill side sounds a bit tricky to implement.
