### ISSUE TITLE
Other options for type in the headings?

### ISSUE THREAD

**Issue by hope-data-science** [rjournal/rjtools#40]
Dear maintainers of **rjtools**, 

In the template, I can find the type is "package". What are the other optional types (e.g. "Reviews and Proposals" as stated in author guideline, is it possible)?

Also, I find it hard to knit the file and could not find the possible reason. Can you take a look for me? (The files resides at <https://github.com/hope-data-science/RJ_reco>)

Thanks.

**Comment by hope-data-science** [comment]
I find that even the template could not work on my laptop, the pdf could not be knitted, with errors listed as below:
```
Detected the following packages from article:
  CRAN: ToOoOlTiPs, plotly, crosstalk, tsibbletalk, palmerpenguins, ggplot2
  Bioconductor: 
Error: CCTZ: Unrecognized output timezone: "Asia/Taipei"
In addition: Warning message:
In output_format$post_knit(front_matter, knit_input, runtime, encoding = "UTF-8") :
  A date must be provided for your article. Defaulting to today's date.

Error: <callr_status_error: callr subprocess failed: LaTeX failed to compile RJwrapper.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJwrapper.log for more info.>
-->
<callr_remote_error in NULL:
 LaTeX failed to compile RJwrapper.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJwrapper.log for more info.>
 in process 292 

 Stack trace:

 Process 26248:
 1. rmarkdown::render("D:/R4BS/paper/RJ/reco/reco.Rmd", encoding = "CP936")
 2. output_format$on_exit()
 3. rjtools:::overlay()
 4. callr::r(function(input) { ...
 5. callr:::get_result(output = out, options)
 6. throw(newerr, parent = remerr[[2]])

 x callr subprocess failed: LaTeX failed to compile RJwrapper.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJwrapper.log for more info. 

 Process 292:
 18. (function (input)  ...
 19. rmarkdown::render(input, output_format = "rjtools::rjournal_pdf_article")
 20. output_format$post_processor(front_matter, input, output_file,  ...
 21. rticles:::post_process(metadata, utf8_input, output_file, clean,  ...
 22. tinytex::latexmk("RJwrapper.tex", base$pandoc$latex_engine, clean = clean)
 23. tinytex:::latexmk_emu(file, engine, bib_engine, engine_args,  ...
 24. tinytex:::run_engine()
 25. tinytex:::system2_quiet(engine, c("-halt-on-error", "-interaction=batchmode ...
 26. tinytex:::on_error()
 27. tinytex:::show_latex_error(file, logfile)
 28. base:::stop(e, " See ", logfile, " for more info.", call. = FALSE)
 29. base:::.handleSimpleError(function (e)  ...
 30. h(simpleError(msg, call))

 x LaTeX failed to compile RJwrapper.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJwrapper.log for more info. 

Execution halted
```

**Comment by hope-data-science** [comment]
Problem have been solved. Some of the problems might occur because special characters exist in the .bib file, it might be better if there is an automatic tool to process this beforehand if possible. Thanks.

**Comment by dicook** [comment]
Thanks Hope - I’m sorry that I didn’t get back to you on the problem.

> On 13 Jun 2022, at 6:34 pm, Hope ***@***.***> wrote:
> 
> 
> Problem have been solved. Some of the problems might occur because special characters exist in the .bib file, it might be better if there is an automatic tool to process this beforehand if possible. Thanks.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by hope-data-science** [comment]
Thank you for noting, I've submitted another article (not type of package). But I lose contact of the status since then, may I ask for the status of the manuscript ([2022-113])? That should be labelled as another type of article, but I could not find the correct parameter and still use the default settings.
