### ISSUE TITLE
create_article() creates html but no pdf

### ISSUE THREAD

**Issue by goodsman** [rjournal/rjtools#44]
I am running on Windows 11 with R version 4.2.1 and Rstudio 2022.02.03 Build 492. 

My understanding is that when rjtools::create_package() is run, a html and pdf file should be created (two output journal types). When I run create_package() and then navigate to the folder, open the markdown document, and click knit in Rstudio, I obtain the following error and no pdf document is created: 

> Output created: quokka-bilby.html

Error: <callr_status_error: callr subprocess failed: argument is of length zero>
-->
<callr_remote_error in if (metadata$volume < 14) {                     ...:
 argument is of length zero>
 in process 1988 

 Stack trace:

 Process 17112:
 1. rmarkdown::render("C:/.../rjarticle/quokka-bilby.Rm ...
 2. output_format$on_exit()
 3. rjtools:::overlay()
 4. callr::r(function(input) { ...
 5. callr:::get_result(output = out, options)
 6. throw(newerr, parent = remerr[[2]])

 x callr subprocess failed: argument is of length zero 

 Process 1988:
 18. (function (input)  ...
 19. rmarkdown::render(input, output_format = "rjtools::rjournal_pdf_article")
 20. output_format$post_processor(front_matter, input, output_file,  ...
 21. base:::.handleSimpleError(function (e)  ...
 22. h(simpleError(msg, call))

 x argument is of length zero 

Warning message:
In output_format$post_knit(front_matter, knit_input, runtime, encoding = "UTF-8") :
  A date must be provided for your article. Defaulting to today's date.
Execution halted

Any idea why this occurs?

**Comment by casperhart** [comment]
I believe this is fixed in the latest development version, see #43

**Comment by mitchelloharawild** [comment]
Closing as this should be fixed. Please re-open with a MRE if this is still an issue.
