### ISSUE TITLE
Filenames inconsistent with the checking process

### ISSUE THREAD

**Issue by bastienchassagnol-servier** [rjournal/rjtools#46]
Dear programmer,

When executing the command _rjtools::create_article(file_name)_, and then knitting the document, the pdf's name is file_name.pdf and not RJwrapper.pdf, yielding an issue when executing command _initial_check_article(path = here::here("rjarticle"))_. Is it the expected behavior? Should we create, addtionally to file_name.pdf, a copy of this document named RJwrapper.pdf?

Sincerely yours,

**Comment by dicook** [comment]
We need to change the check now because we don’t need RJwrapper.pdf any more

**Comment by bastienchassagnol-servier** [comment]
Irrelevant check has been removed, thanks
