### ISSUE TITLE
Check for introduction is case-sensitive

### ISSUE THREAD

**Issue by blernermhc** [rjournal/rjtools#51]
The check to find the introduction section looks for introduction in all lowercase.  If the section is simply called "Introduction", or begins with the word "Introduction", the test will report that the introduction section is missing.

**Comment by huizezhang-sherry** [comment]
Hi, can you specify which check function fails you? 

The sample article generated from `create_article()` has an introduction section named "Introduction". It should pass the tests relevant to the introduction.

**Comment by blernermhc** [comment]
Here is a simple tex document that reports the error.  My Latex file was created by hand, not using create_article.  This is for rjtools 1.0.3

\title{Good Stuff}
\author{by some people}

\maketitle

\abstract{
Something here
}

\section{Introduction}

Something else here

**Comment by huizezhang-sherry** [comment]
Changing

\section{Introduction}

to 

\hypertarget{introduction}{
\section{Introduction}\label{introduction}}

will allow you to pass the test.

**Comment by dicook** [comment]
It is probably not a good idea to change the tex file to add the extra lines. 

Our check should just look at the text inside the \section{} function? I am guessing that the additional functions (\hypertarget, \label) are generated by pandoc from the Rmd template. And our check is assuming that it is in this form. If so we should simplify the check function.

> On 14 Nov 2022, at 9:27 am, Sherry Zhang ***@***.***> wrote:
> 
> 
> Changing
> 
> \section{Introduction}
> 
> to
> 
> \hypertarget{introduction}{
> \section{Introduction}\label{introduction}}
> 
> will allow you to pass the test.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by huizezhang-sherry** [comment]
The check should now work with `\section{Introduction}` in tex.
