### ISSUE TITLE
check that functions can work alone as well as in composite

### ISSUE THREAD

**Issue by dicook** [rjournal/rjtools#6]
I made all functions exported so an author can run any individual check themselves this means that the arguments might need to change to make this easier. 

also noticed that the "ERROR: The title is not in title case!" will occur if a title has a package name in all caps so perhaps we just want to make this a warning to check for themselves

**Comment by huizezhang-sherry** [comment]
restructure the arguments in  commit 5abf72b2cca7319353e11d279fdf409aafded288 

* `check_*` functions for separate checks
* `initial_check_article` for running all the checks and outputs a log file
