### ISSUE TITLE
Namespace errors on knitting example article. 

### ISSUE THREAD

**Issue by kristyrobledo** [rjournal/rjtools#60]
Hi. Im trying to run the example and knit this before writing an article. 

I've installed rjtools , and run:

> library(rjtools) 
> create_article("test.Rmd")
 [1] "D68D5183" 

then I go to the top and hit "knit" and I get this in my render window:

Error in namespaceExport(ns, exports) : 
  undefined exports: create_article, create_blog, create_post, create_theme, create_website, distill_article, distill_website, import_post, publish_website, rename_post_dir, update_post
Calls: <Anonymous> ... do.call -> <Anonymous> -> loadNamespace -> namespaceExport
Execution halted

Not sure if this is me missing something simple? Thanks for looking into it. 

Session info:

> sessionInfo() 
R version 4.1.3 (2022-03-10) 
Platform: x86_64-w64-mingw32/x64 (64-bit) 
Running under: Windows 10 x64 (build 19045)  
Matrix products: default  locale:
 [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
 [4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252      

attached base packages: 
[1] stats     graphics  grDevices utils     datasets  methods   base       

other attached packages: 
[1] rjtools_1.0.10 
loaded via a namespace (and not attached):  
[1] Rcpp_1.0.10         compiler_4.1.3      BiocManager_1.30.20 tools_4.1.3         digest_0.6.31        
[6] jsonlite_1.8.4      evaluate_0.20       lifecycle_1.0.3     viridisLite_0.4.1   rlang_1.0.6       
  [11] cli_3.6.0           rstudioapi_0.14     yaml_2.3.7          hunspell_3.0.2      xfun_0.37         
  [16] yesno_0.1.2         fastmap_1.1.1       kableExtra_1.3.4    httr_1.4.5          stringr_1.5.0   
    [21] xml2_1.3.3          knitr_1.42          fs_1.6.1            vctrs_0.5.2         systemfonts_1.0.4  
 [26] cranlogs_2.1.1      webshot_0.5.4       svglite_2.1.0       glue_1.6.2          R6_2.5.1          
  [31] rmarkdown_2.20      purrr_1.0.1         magrittr_2.0.3      scales_1.2.1        htmltools_0.5.4 
    [36] rvest_1.0.3         colorspace_2.0-3    stringi_1.7.12      munsell_0.5.0
--

**Comment by dicook** [comment]
I think using “.Rmd” in the create_article() has caused the problem. Use just the stem “test”. 

> On 7 Mar 2023, at 3:57 pm, Kristy Robledo ***@***.***> wrote:
> 
> 
> Hi. Im trying to run the example and knit this before writing an article.
> 
> I've installed rjtools , and run:
> 
> library(rjtools)
> create_article("test.Rmd")
> [1] "D68D5183"
> 
> then I go to the top and hit "knit" and I get this in my render window:
> 
> Error in namespaceExport(ns, exports) :
> undefined exports: create_article, create_blog, create_post, create_theme, create_website, distill_article, distill_website, import_post, publish_website, rename_post_dir, update_post
> Calls: ... do.call -> -> loadNamespace -> namespaceExport
> Execution halted
> 
> Not sure if this is me missing something simple? Thanks for looking into it.
> 
> Session info:
> 
> sessionInfo()
> R version 4.1.3 (2022-03-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19045)
> Matrix products: default locale:
> [1] LC_COLLATE=English_Australia.1252 LC_CTYPE=English_Australia.1252 LC_MONETARY=English_Australia.1252
> [4] LC_NUMERIC=C LC_TIME=English_Australia.1252
> 
> attached base packages:
> [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages:
> [1] rjtools_1.0.10
> loaded via a namespace (and not attached):
> [1] Rcpp_1.0.10 compiler_4.1.3 BiocManager_1.30.20 tools_4.1.3 digest_0.6.31
> [6] jsonlite_1.8.4 evaluate_0.20 lifecycle_1.0.3 viridisLite_0.4.1 rlang_1.0.6
> [11] cli_3.6.0 rstudioapi_0.14 yaml_2.3.7 hunspell_3.0.2 xfun_0.37
> [16] yesno_0.1.2 fastmap_1.1.1 kableExtra_1.3.4 httr_1.4.5 stringr_1.5.0
> [21] xml2_1.3.3 knitr_1.42 fs_1.6.1 vctrs_0.5.2 systemfonts_1.0.4
> [26] cranlogs_2.1.1 webshot_0.5.4 svglite_2.1.0 glue_1.6.2 R6_2.5.1
> [31] rmarkdown_2.20 purrr_1.0.1 magrittr_2.0.3 scales_1.2.1 htmltools_0.5.4
> [36] rvest_1.0.3 colorspace_2.0-3 stringi_1.7.12 munsell_0.5.0
> 
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by kristyrobledo** [comment]
thanks @dicook. I tried  
create_article("test")
then "knit" and unfortunately got the same error. 
I did try the github version of rjtools as well as CRAN, same error.

**Comment by dicook** [comment]
Oh, someone suggested you need to install distill then.

> On 7 Mar 2023, at 5:07 pm, Kristy Robledo ***@***.***> wrote:
> 
> 
> thanks @dicook. I tried
> create_article("test")
> then "knit" and unfortunately got the same error.
> I did try the github version of rjtools as well as CRAN, same error.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by kristyrobledo** [comment]
thanks - I uninstalled distill, turned computer off and on again, reinstalled and viola. Thanks - ill close the issue!
