### ISSUE TITLE
Use section numbering consistently in PDF versions

### ISSUE THREAD

**Issue by zeileis** [rjournal/rjtools#61]
The `RJournal.sty` shipped in `rjtools` was updated last year to provide section numbers also in PDF versions of R Journal contributions: https://github.com/rjournal/rjtools/commit/c07c4590d53d45a85ef2d5506e4ced42f8dbcc93 Note, however, that this update hasn't propagated everywhere:

- First, it hasn't been passed on to the `rticles` package. I have reported the inconsistency as an issue in their package as well: https://github.com/rstudio/rticles/issues/517
- Second, it is not shipped in the old-style LaTeX templates at https://journal.r-project.org/share/RJtemplate.zip

I'm not sure whether there are other versions floating around that should be updated.

I would also recommend to explicitly create a new version for this. The file claims to be

    \ProvidesPackage{RJournal}[2013/08/27 v0.13 RJournal package]

but it really isn't anymore. This may create confusion and you may also end up using the wrong style file. For example, David Kaplan's `knitrdata` paper in the most recent R Journal volume does not have section numbers in the PDF version: https://journal.R-project.org/articles/RJ-2023-001/RJ-2023-001.pdf Checking the underlying sources, it turns out that he included an `RJournal.sty` version that still excluded version numbering. Of course, this may have been a conscious decision but probably not. See: https://github.com/rjournal/rjournal.github.io/blob/master/_articles/RJ-2023-001/RJournal.sty#L106

**Comment by mitchelloharawild** [comment]
Thanks for reporting this issue for the `rticles` maintainers, I am unsure if they plan to continue providing the rjournal article format in their package as we encourage submissions in the rjtools HTML/PDF format.

@dicook - could we update this `RJtemplate.zip` resource for changes to `RJournal.sty`?

I will bump the version, thank you for this. I am somewhat unfamiliar with tex package formalities.
