### ISSUE TITLE
rjtools does not generate HTML file when bibliography file is included

### ISSUE THREAD

**Issue by technOslerphile** [rjournal/rjtools#75]
I have my bibliography file `RJreferences.bib` and when I try to knit the RMD file, it returns the corresponding LaTeX PDF file, but there is no HTML file. If I omit the bibliography keyword from the RMD file and then knit again, both HTML and PDF outputs are generated. But of course, there wouldn't any references. Attached is a zip file containing a sample RMD file and RJreferences.bib for reproducing the issue. 

[error-latex.zip](https://github.com/rjournal/rjtools/files/12134109/error-latex.zip)

**Comment by s-u** [comment]
Sorry, this works just fine for me. Please be more specific such as how you tried to render it, full error output, versions of R and the tools, etc.

**Comment by technOslerphile** [comment]
> Sorry, this works just fine for me. Please be more specific such as how you tried to render it, full error output, versions of R and the tools, etc.

I have the RMD file open in RStudio and I click `Knit`. Then it starts rendering and after few seconds the output files are generated in the same folder. But no HTML file. If it makes it any easier, I attach the RJwrapper.log here. 

[RJwrapper.log](https://github.com/rjournal/rjtools/files/12135712/RJwrapper.log)

**Comment by mitchelloharawild** [comment]
I also can't reproduce this issue with your example. Try updating your software and let us know if you're still having trouble.
