### ISSUE TITLE
is it possible to make it easy for people to see the sample paper?

### ISSUE THREAD

**Issue by dicook** [rjournal/rjtools#8]
could we put it in the pkg down site for example?

**Comment by dicook** [comment]
- create function should create the minimal template, the lovely toooooltips paper. 
- main page should use remotes, and should install rjdistill too
- sample paper should show up on web site
- vignette needs to be on web site
- create paper example code should be on main web page site
-

**Comment by huizezhang-sherry** [comment]
changes made in 20aba02d53c763386fbd563847279d4e16b7ec48, 2e612dcbeab3407d222f64913541a06046e68ac9, and b231770f061e510a77d06cca422356bdd02f3c0b

"sample paper should show up on web site" to be implemented
