### ISSUE TITLE
JG: tikz conversion with tex to html convertor?

### ISSUE THREAD

**Issue by hturner** [rjournal/rjtools#80]
Comment from @ajrgodfrey:

> tikz conversion may be handled by one of tex to html convertors - could this be a simpler/better implementation than what we have?

**Comment by ajrgodfrey** [comment]
Might be worth seeing what arXiv is doing here.

From: Heather Turner ***@***.***>
Sent: Friday, September 8, 2023 2:11 AM
To: rjournal/rjtools ***@***.***>
Cc: Jonathan Godfrey ***@***.***>; Mention ***@***.***>
Subject: [rjournal/rjtools] JG: tikz conversion with tex to html convertor? (Issue #80)


Comment from @ajrgodfrey<https://github.com/ajrgodfrey>:

tikz conversion may be handled by one of tex to html convertors - could this be a simpler/better implementation than what we have?

-

**Comment by hturner** [comment]
put on wrong repo
