### ISSUE TITLE
Better alt text for ORCID logos

### ISSUE THREAD

**Issue by hturner** [rjournal/rjtools#86]
Comment from @ajrgodfrey

> Currently the alt text for ORCID logos is `alt="ORCID ID"`. This is uninformative as it is the same for all authors. Ideally it would say, e.g. "ORCID for Diane Cook".

**Comment by dicook** [comment]
This is a distill package issue. Copied onto that site.

**Comment by cderv** [comment]
I have now done this in https://github.com/rstudio/distill/commit/f8c1a54cf0ab45750ef5774e2fc4462864f395ee so you can try it with dev version of **distill**

I followed @ajrgodfrey suggestion to add author name e.g "ORCID ID for Diane Cook"

**Comment by mitchelloharawild** [comment]
Great, thanks!
