### ISSUE TITLE
Consider using numbered headers throughout

### ISSUE THREAD

**Issue by hturner** [rjournal/rjtools#89]
Comment from @ajrgodfrey

> The new R Journal style uses numbered sections and unnumbered sub-sections. The legacy LaTeX style uses no numbering, but numbering can be helpful for people to reference particular sections. It can also highlight issues such as use of incorrect header levels (e.g. jumping from h2 to h4 rather than h3).

**Comment by dicook** [comment]
Plan is to go to two levels of numbering. Numbering starting from level 2 (h2) needs to be fixed for both PDF and HTML
