### ISSUE TITLE
Use true horizontal rules

### ISSUE THREAD

**Issue by hturner** [rjournal/rjtools#92]
Comment from @ajrgodfrey

> The current style uses top and bottom borders to create horizontal separators. Using true horizontal separators, i.e. `<hr>` tags in the HTML, would enable navigation with a screen reader, to jump between these horizontal separators to reach different parts of the document.

**Comment by dicook** [comment]
This is best handled by distill

**Comment by mitchelloharawild** [comment]
Resolved by https://github.com/rstudio/distill/issues/495
